# Site settings
title: Open Supporter Data Interface
email: your-email@domain.com
description: "The Open Supporter Data Interface (OSDI) effort seeks to define an API and data structures for interoperability among products in the progressive cause-based, campaign and non-profit marketplace."
baseurl: ""
url: "http://opensupporter.org/"

# Build settings
markdown: kramdown
permalink: pretty
kramdown:
    input: GFM
